name: imaging_course_day5_2023
channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - conda-forge::ipywidgets==8.0.4
  - pip
  - pip:
    - cellpose==2.2.1
    - matplotlib==3.7.1
    - ome-zarr==0.7.1
    - pandas==2.0.1
    
