name: imaging_course_minio_day5_2023
channels:
  - bioconda
  - conda-forge
  - defaults
  - ome
  - joshmoore
dependencies:
  - python == 3.9.*
  - go-mc==2020.11.17
  - pip
  - pip:
    - napari[all]
    - napari-ome-zarr==0.5.2

